### ISSUE TITLE
Map records with ID

### ISSUE THREAD

**Issue by DriesS** [autotelik/datashift#27]
I exported my list of products ( not spree but custom made application) that have all an ID, when I import the excel file again with my changes ( description ), he tells me that there is a duplicate entry with ID x.

Is it possible with datashift to map an existing record with the ID, so when the ID exists that he updates the row with that specific ID with the values? We want to use the excel file to keep the products up to date on the website because the client is working internaly with this excel sheet.

**Comment by autotelik** [comment]
Created new 'feature' to monitor this so closing
