### ISSUE TITLE
Not working with Spree 3.0.5 stable

### ISSUE THREAD

**Issue by sanjaygoel** [autotelik/datashift#36]
My thor file looks like this:
```
require 'datashift'
require 'datashift_spree'
DataShift::load_commands
DataShift::SpreeHelper::load_commands
```
My Gemfile looks like this
```
gem 'spree', github: 'spree/spree', branch: '3-0-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
gem 'datashift'
gem 'datashift_spree'
```
When I do `bundle exec thor list datashift`
I get

> WARNING: unable to load thorfile "/home/sanjay/git/growchef/growchef.thor": uninitialized constant DataShift::Logging
> /home/sanjay/.rvm/gems/ruby-2.2.1/gems/datashift-0.15.0/lib/datashift/method_mapper.rb:22:in `<class:MethodMapper>'
> No Thor commands available

Please help. 

Thanks
Sanjay

**Comment by sybind** [comment]
Hi Sanjay,

I just ran into this problem. In your gemfile, point to the github address, like this:
```
gem 'datashift_spree', :git => "git://github.com/autotelik/datashift_spree"
```

It seems whatever in on rubygems is not up to date.

**Comment by autotelik** [comment]
rubygems is now up to date with master ... but I am working on a complete rewrite so this iteration will not be maintained and will shortly be superseded by split_into_concerns branch
