### ISSUE TITLE
FR: Admin gui for import/export

### ISSUE THREAD

**Issue by craft37** [autotelik/datashift#39]
Hello.
Recently you had a plans in todo to make a gui for importing/exporting.
Could we know some news about it?
Thanks.

**Comment by autotelik** [comment]
hi ... I've been rewriting the main API so had no time for this, next will focus back on the Spree specific imports and then maybe look at an engine for Rails with a GUI. If anyone wanted to have a go I'd be happy to help/advise

cheers
tom
