### ISSUE TITLE
validations issue 

### ISSUE THREAD

**Issue by Tenzil** [autotelik/datashift#44]
Hey thanks for providing this great stuff, I have query when i upload some products via xls. I got error 

> WARNING : Check logs : 1 rows contained errors
 which is expected as it was failing spree validation. I am sending a mail as soon the background process completes. 
But the issue is that warning  is not raising any exception such that i can rescue it and send failure mail.

In simple term, i want to send success  mail when product uploaded successfully  and failure mail when the upload  fails

**Comment by autotelik** [comment]
hi .. thanks! 

Ok this is an interesting idea, can't look too deeply now but short term you may need to fork or create your own loader inheriting from one od the main Loaders and add something to `report` to check the final status and send your mail. The class involved in storing details of rows with errors or success, is  Reporter under : lib/loaders/reporter.rb

The reporter can be accessed in any  Loader via the  `reporter` method - which reaches through to main reporter instance which lives in current Document Context (DocContext in lib/datashift/doc_context.rb

For example in the ExcelLoader after the final row has been processed it calls
```
    ensure
        report
      end
```
Which calls on LoaderBase method :
```
    def report
      reporter.report
    end
```
This report methods dumps out the WARNING you see above, so perhaps  you could over-ride this `report` and add your own mail stuff in there

Thanks for the ideas, I need more real world examples to help shape the development, so I will think about adding some hooks to reporter so you can trigger your own reports more easily but this may take a while as very busy :-)

cheers
tom

**Comment by Tenzil** [comment]
Hi tom,
Thanks for the reply. I didn't expect the reply this fast. I have started explored datashift reporter which you are talking about. I tried adding the mailer code in https://github.com/autotelik/datashift/blob/f5815a6b9b8235f5b4d691d3a3eda6b3e92773be/lib/loaders/reporter.rb#L51 method. It worked fine (i overridden that file in my initializer(added a line)). Then i thought  instead of doing that, i can add my code here such that i can say these many products failed https://github.com/autotelik/datashift/blob/f5815a6b9b8235f5b4d691d3a3eda6b3e92773be/lib/loaders/paperclip/attachment_loader.rb#L192  . But the issue now is I am getting argument error in initializer .
Can't i override it? Please explain. Sorry for disturbing you in a busy day

**Comment by Tenzil** [comment]
HI Tom,
I am getting some error when i trying override excel_loader.rb, in initialzer,

> /config/initializers/datashift/excel_loader.rb:12:in `require_relative': cannot load such file 
Please can you let me know how to override this particular file

**Comment by Tenzil** [comment]
Hi Tom,
Me again, Is it possible you to add an extra column (errors along with validation errors in it) in MissingRecord folder you are creating by the end of the upload.
https://github.com/autotelik/datashift/blob/master/lib/loaders/excel_loader.rb#L106
I am unable to override it, too much file required in that class. Or please explain how to override it.

**Comment by autotelik** [comment]
Hi ... could you post your code, or a temp link to it, I can't really tell what's going on without understanding what you are trying to do

I will try to make Reporter more user friendly so its behaviour can be added to etc but in meantime to dirty monkey patch ...

I would normally  re-open the class to over ride a method 
```
DataShift::Reporter.class_eval do

alias_method :original_report, :report

  def report
    original_report

    do email stuff
  end

end
```

**Comment by Tenzil** [comment]
Hi .. I done with mail part. I just asking is it possible to add extra column in xls sheet in (MissingAttachmentRecords) saying that these records are not uploaded due to validation errors(example 'sku already taken')

**Comment by autotelik** [comment]
so you want to write to the same xls file you are loading ?

The failed object and current node context (holds the row and colum numbers etc)  are available to you in the reporter lib/datashift/doc_context.rb but bit messy right now

I'll look at adding a better container for errors but for now you probaly have to over     def failure( error_messages, _delete_object = true)

and use the context to give you the row/column that failed so you can insert a new column in the row

**Comment by autotelik** [comment]
To over ride a loader, you can  create a new loader class that inherits from ExceLoader - as the import tasks should all take a --loader option to enable you to specify the Loader class to use

**Comment by autotelik** [comment]
hi .. fyi .. just pushed some changes as a start for better architecture for reporting .. 

split the concepts in two, so the data is now collected by a progress_monitor and now  the context can  hold MANY reporters, so you can easily add your own reporter to the chain e.g to do emails

in DocContext now
attr_accessor :progress_monitor, :reporters

thanks for the feedback as this is really useful,  to understand what people need in real world situations and how to improve the code 

cheers
tom
