### ISSUE TITLE
Rails 5 support?

### ISSUE THREAD

**Issue by flyfy1** [autotelik/datashift#53]
Currently, the gem is dependent upon Rails 4.2

Any plan to support Rails 5? Thx :)

**Comment by autotelik** [comment]
Hi .. I'm not sponsored or anything for this, so afraid development a bit slow  but yes, will definitely look at creating a  5 branch and upgrading

cheers
tom

**Comment by flyfy1** [comment]
Ahh OK no worries, just asking :) Thx for the reply

**Comment by autotelik** [comment]
no worries, was just getting  my excuses in early :-) 

TBH if I know people are using it and asking for stuff, then galvanizes me to do something so 5 support coming up  :-)

**Comment by autotelik** [comment]
Master gemspec now allows for Rails 5.   Untested in real world app but all specs passing
