### ISSUE TITLE
Docs on how to config mapper / loader?

### ISSUE THREAD

**Issue by flyfy1** [autotelik/datashift#54]
Currently we have wiki: [Options and Configuration](https://github.com/autotelik/datashift/wiki/Options-and-configuration), but it's quite incomplete.

I want to learn how to:

- configure the loader to map data into specific field / nested resource, from the excel column
- configure the mapper to output the data

**Comment by autotelik** [comment]
Wiki updated but will probably always lag the code a little.

I did alot of work on the internal API to make configuration easier but still some way to go to make loader mappoign really excellent.

To get info, I'd say for now the specs and spec/dummy rails app are good places to check API, best practice etc

cheers
tom
