### ISSUE TITLE
Undefined method 'type_cast_from_database'

### ISSUE THREAD

**Issue by ouykjh** [autotelik/datashift#59]
While I'm trying to parse csv file I received ```#<NoMethodError: undefined method `type_cast_from_database' for #<ActiveRecord::ConnectionAdapters::Column:0x007fd36dc5f358>>```
Probably it's problem with rails 5 where this method for column is removed. Do you know any simple solution to fix it? Do you plan to release new, rails 5 compatible, datashift version?

**Comment by autotelik** [comment]
Sorry I never got back to you. Missed this. But yes, closing as I have tried to make sure latest versions work with Rails 5
